FORMAT: 1A
HOST: http://browser.ihtsdotools.org/api

# SNOMED CT Snapshot API v2
The SNOMED CT Snapshot REST API provides access to SNOMED CT content snapshot form (only the latest version for all components, see Snapshot definition in the RF2 format description).

This API has been developed by SNOMED International to support lightweight deployments of read-only SNOMED CT terminology servers.

# Group Concepts
Concepts allows access to **SNOMED CT Concepts**

## Concept [/v2/snomed/{edition}/{release}/concepts/{sctid}]
A single Concept with all its details

+ Parameters
    + edition (required, string, `en-edition`) ... Identifier for the SNOMED CT Edition to browse, for example `en-edition` for the International Edition
    + release (required, string, `v20170731`) ... Identifier for the release, usually the release effective time preceded with a `v`.
    + sctid (required, number, `79859009`) ... SNOMED CT Identifier of the concept to retrieve.

### Retrieve a Concept [GET]
+ Response 200 (application/json)

    + Body

            {
                "_id": "59d8cf1ee63829a42851a1ca",
                "memberships": [
                {
                    "type": "SIMPLEMAP",
                    "referencedComponentId": "79859009",
                    "refset":
                    {
                        "conceptId": "900000000000497000",
                        "preferredTerm": "CTV3 simple map"
                    },
                    "otherValue": "02B3.",
                    "uuid": "92ca1e61-fff8-51d2-a11c-545d83797bbc",
                    "active": true,
                    "effectiveTime": "20020131",
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                }],
                "descriptions": [
                {
                    "descriptionId": "132493010",
                    "conceptId": "79859009",
                    "type":
                    {
                        "conceptId": "900000000000013009",
                        "preferredTerm": "Synonym"
                    },
                    "languageCode": "en",
                    "term": "Computer programmer",
                    "length": 19,
                    "caseSignificance":
                    {
                        "conceptId": "900000000000448009",
                        "preferredTerm": "Case insensitive"
                    },
                    "acceptability": [
                    {
                        "descriptionId": "132493010",
                        "languageReferenceSet":
                        {
                            "conceptId": "900000000000508004",
                            "preferredTerm": "GB English"
                        },
                        "acceptability":
                        {
                            "conceptId": "900000000000548007",
                            "preferredTerm": "Preferred"
                        },
                        "uuid": "599edffd-9492-57c2-a615-212f9916e23d",
                        "active": true,
                        "effectiveTime": "20020131",
                        "module":
                        {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core"
                        }
                    },
                    {
                        "descriptionId": "132493010",
                        "languageReferenceSet":
                        {
                            "conceptId": "900000000000509007",
                            "preferredTerm": "US English"
                        },
                        "acceptability":
                        {
                            "conceptId": "900000000000548007",
                            "preferredTerm": "Preferred"
                        },
                        "uuid": "63ea720a-e2c4-5e85-9758-4536606ad0b3",
                        "active": true,
                        "effectiveTime": "20080131",
                        "module":
                        {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core"
                        }
                    }],
                    "active": true,
                    "effectiveTime": "20170731",
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "descriptionId": "504232014",
                    "conceptId": "79859009",
                    "type":
                    {
                        "conceptId": "900000000000013009",
                        "preferredTerm": "Synonym"
                    },
                    "languageCode": "en",
                    "term": "Computer programr",
                    "length": 17,
                    "caseSignificance":
                    {
                        "conceptId": "900000000000020002",
                        "preferredTerm": "Initial character case insensitive"
                    },
                    "active": false,
                    "effectiveTime": "20080131",
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "descriptionId": "820955016",
                    "conceptId": "79859009",
                    "type":
                    {
                        "conceptId": "900000000000003001",
                        "preferredTerm": "Fully specified name"
                    },
                    "languageCode": "en",
                    "term": "Computer programmer (occupation)",
                    "length": 32,
                    "caseSignificance":
                    {
                        "conceptId": "900000000000448009",
                        "preferredTerm": "Case insensitive"
                    },
                    "acceptability": [
                    {
                        "descriptionId": "820955016",
                        "languageReferenceSet":
                        {
                            "conceptId": "900000000000508004",
                            "preferredTerm": "GB English"
                        },
                        "acceptability":
                        {
                            "conceptId": "900000000000548007",
                            "preferredTerm": "Preferred"
                        },
                        "uuid": "26b45dfb-3d13-52c4-b6c5-f3cab43b5ad6",
                        "active": true,
                        "effectiveTime": "20020131",
                        "module":
                        {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core"
                        }
                    },
                    {
                        "descriptionId": "820955016",
                        "languageReferenceSet":
                        {
                            "conceptId": "900000000000509007",
                            "preferredTerm": "US English"
                        },
                        "acceptability":
                        {
                            "conceptId": "900000000000548007",
                            "preferredTerm": "Preferred"
                        },
                        "uuid": "772accf1-7627-5366-b1b8-1f246416521e",
                        "active": true,
                        "effectiveTime": "20020131",
                        "module":
                        {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core"
                        }
                    }],
                    "active": true,
                    "effectiveTime": "20170731",
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                }],
                "relationships": [
                {
                    "relationshipId": "4076360022",
                    "type":
                    {
                        "conceptId": "116680003",
                        "preferredTerm": "Is a"
                    },
                    "destination":
                    {
                        "conceptId": "106297009",
                        "preferredTerm": "Statistician, mathematician, systems analyst AND/OR related technician",
                        "fullySpecifiedName": "Statistician, mathematician, systems analyst/related technician (occupation)",
                        "definitionStatus":
                        {
                            "conceptId": "900000000000074008",
                            "preferredTerm": "Primitive"
                        },
                        "statedDescendants": 13,
                        "inferredDescendants": 13,
                        "active": true,
                        "effectiveTime": "20020131",
                        "module":
                        {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core"
                        }
                    },
                    "sourceId": "79859009",
                    "relationshipGroup": 0,
                    "characteristicType":
                    {
                        "conceptId": "900000000000010007",
                        "preferredTerm": "Stated relationship"
                    },
                    "modifier":
                    {
                        "conceptId": "900000000000451002",
                        "preferredTerm": "Some"
                    },
                    "active": true,
                    "effectiveTime": "20080731",
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "relationshipId": "4076361021",
                    "type":
                    {
                        "conceptId": "116680003",
                        "preferredTerm": "Is a"
                    },
                    "destination":
                    {
                        "conceptId": "158832009",
                        "preferredTerm": "Systems analyst/computer programmer",
                        "fullySpecifiedName": "Systems analyst/computer programmer (occupation)",
                        "definitionStatus":
                        {
                            "conceptId": "900000000000074008",
                            "preferredTerm": "Primitive"
                        },
                        "statedDescendants": 4,
                        "inferredDescendants": 4,
                        "active": true,
                        "effectiveTime": "20020131",
                        "module":
                        {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core"
                        }
                    },
                    "sourceId": "79859009",
                    "relationshipGroup": 0,
                    "characteristicType":
                    {
                        "conceptId": "900000000000010007",
                        "preferredTerm": "Stated relationship"
                    },
                    "modifier":
                    {
                        "conceptId": "900000000000451002",
                        "preferredTerm": "Some"
                    },
                    "active": true,
                    "effectiveTime": "20080731",
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "relationshipId": "277869024",
                    "type":
                    {
                        "conceptId": "116680003",
                        "preferredTerm": "Is a"
                    },
                    "destination":
                    {
                        "conceptId": "158832009",
                        "preferredTerm": "Systems analyst/computer programmer",
                        "fullySpecifiedName": "Systems analyst/computer programmer (occupation)",
                        "definitionStatus":
                        {
                            "conceptId": "900000000000074008",
                            "preferredTerm": "Primitive"
                        },
                        "statedDescendants": 4,
                        "inferredDescendants": 4,
                        "active": true,
                        "effectiveTime": "20020131",
                        "module":
                        {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core"
                        }
                    },
                    "sourceId": "79859009",
                    "relationshipGroup": 0,
                    "characteristicType":
                    {
                        "conceptId": "900000000000011006",
                        "preferredTerm": "Inferred relationship"
                    },
                    "modifier":
                    {
                        "conceptId": "900000000000451002",
                        "preferredTerm": "Some"
                    },
                    "active": true,
                    "effectiveTime": "20020131",
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "relationshipId": "277870020",
                    "type":
                    {
                        "conceptId": "116680003",
                        "preferredTerm": "Is a"
                    },
                    "destination":
                    {
                        "conceptId": "106297009",
                        "preferredTerm": "Statistician, mathematician, systems analyst AND/OR related technician",
                        "fullySpecifiedName": "Statistician, mathematician, systems analyst/related technician (occupation)",
                        "definitionStatus":
                        {
                            "conceptId": "900000000000074008",
                            "preferredTerm": "Primitive"
                        },
                        "statedDescendants": 13,
                        "inferredDescendants": 13,
                        "active": true,
                        "effectiveTime": "20020131",
                        "module":
                        {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core"
                        }
                    },
                    "sourceId": "79859009",
                    "relationshipGroup": 0,
                    "characteristicType":
                    {
                        "conceptId": "900000000000011006",
                        "preferredTerm": "Inferred relationship"
                    },
                    "modifier":
                    {
                        "conceptId": "900000000000451002",
                        "preferredTerm": "Some"
                    },
                    "active": true,
                    "effectiveTime": "20020131",
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                }],
                "isLeafInferred": true,
                "isLeafStated": true,
                "v": "2",
                "conceptId": "79859009",
                "preferredTerm": "Computer programmer",
                "fullySpecifiedName": "Computer programmer (occupation)",
                "definitionStatus":
                {
                    "conceptId": "900000000000074008",
                    "preferredTerm": "Primitive"
                },
                "statedDescendants": 0,
                "inferredDescendants": 0,
                "active": true,
                "effectiveTime": "20020131",
                "module":
                {
                    "conceptId": "900000000000207008",
                    "preferredTerm": "SNOMED CT core"
                }
            }


## Children [/v2/snomed/{edition}/{release}/concepts/{sctid}/children?form={form}]
Lists all children of a concept, in the SNOMED CT hierarchy. Each child is retrieved in a summary form, called Concept Descriptor.

+ Parameters
    + edition (required, string, `en-edition`) ... Identifier for the SNOMED CT Edition to browse, for example `en-edition` for the International Edition
    + release (required, string, `v20170731`) ... Identifier for the release, usually the release effective time preceded with a `v`.
    + sctid (required, number, `123037004`) ... SNOMED CT Identifier of the concept to retrieve.
    + form (required, string, `inferred`) ... Characteristic type of the Is-a hierarchy, either `stated` or `inferred`.

### Retrieve Children [GET]
+ Response 200 (application/json)

    + Body

            [
                {
                    "_id": "59d8ceaae63829a4284df164",
                    "isLeafInferred": false,
                    "isLeafStated": false,
                    "v": "2",
                    "conceptId": "442083009",
                    "preferredTerm": "Anatomical or acquired body structure",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 32818,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8ceb2e63829a4284e300d",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "87100004",
                    "preferredTerm": "Topography unknown",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8cef5e63829a4285050fd",
                    "isLeafInferred": false,
                    "isLeafStated": false,
                    "v": "2",
                    "conceptId": "258331007",
                    "preferredTerm": "Anatomical site notations for tumor staging",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 17,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8cf15e63829a42851575f",
                    "isLeafInferred": false,
                    "isLeafStated": false,
                    "v": "2",
                    "conceptId": "118956008",
                    "preferredTerm": "Morphologically altered structure",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 4952,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8cf1be63829a42851855a",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "361083003",
                    "preferredTerm": "Normal anatomy",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8cf27e63829a42851e77c",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "21229009",
                    "preferredTerm": "Topography not assigned",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8cf28e63829a42851ef13",
                    "isLeafInferred": false,
                    "isLeafStated": false,
                    "v": "2",
                    "conceptId": "91832008",
                    "preferredTerm": "Anatomical organizational pattern",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 35,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8cf79e63829a428546fa3",
                    "isLeafInferred": false,
                    "isLeafStated": false,
                    "v": "2",
                    "conceptId": "278001007",
                    "preferredTerm": "Nonspecific site",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 1,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                }
            ]



## Parents [/v2/snomed/{edition}/{release}/concepts/{sctid}/parents?form={form}]
Lists all parents of a concept, in the SNOMED CT hierarchy. Each parent is retrieved in a summary form, called Concept Descriptor.

+ Parameters
    + edition (required, string, `en-edition`) ... Identifier for the SNOMED CT Edition to browse, for example `en-edition` for the International Edition
    + release (required, string, `v20170731`) ... Identifier for the release, usually the release effective time preceded with a `v`.
    + sctid (required, number, `79859009`) ... SNOMED CT Identifier of the concept to retrieve.
    + form (required, string, `inferred`) ... Characteristic type of the Is-a hierarchy, either `stated` or `inferred`.

### Retrieve Parents [GET]
+ Response 200 (application/json)

    + Body

            [
                {
                    "conceptId": "158832009",
                    "preferredTerm": "Systems analyst/computer programmer",
                    "fullySpecifiedName": "Systems analyst/computer programmer (occupation)",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    },
                    "statedDescendants": 4
                },
                {
                    "conceptId": "106297009",
                    "preferredTerm": "Statistician, mathematician, systems analyst AND/OR related technician",
                    "fullySpecifiedName": "Statistician, mathematician, systems analyst/related technician (occupation)",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    },
                    "statedDescendants": 13
                }
            ]


## Members [/v2/snomed/{edition}/{release}/concepts/{sctid}/members?limit={limit}&paginate={page}]
Lists all reference set members of a concept. Each member is retrieved in a summary form, called Concept Descriptor.
Only concepts that are reference sets will include members.
The concept details describe all the reference sets where a concept is member in, called memberships, and can be retrieved with the /concepts/id call.

+ Parameters
    + edition (required, string, `en-edition`) ... Identifier for the SNOMED CT Edition to browse, for example `en-edition` for the International Edition
    + release (required, string, `v20170731`) ... Identifier for the release, usually the release effective time preceded with a `v`.
    + sctid (required, number, `721144007`) ... SNOMED CT Identifier of the concept to retrieve.
    + limit (optional, number, `5`) ... Number of concepts to retrieve on this call (page size).
    + page (optional, number, `1`) ... Page number to retrieve.

### Retrieve Reference set members [GET]
+ Response 200 (application/json)

    + Body

            {
                "members": [
                {
                    "_id": "59d8ceaae63829a4284df177",
                    "isLeafInferred": false,
                    "isLeafStated": false,
                    "v": "2",
                    "conceptId": "441935006",
                    "preferredTerm": "Acquired absence of all teeth",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 19,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8ceabe63829a4284df6d2",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "234973008",
                    "preferredTerm": "Submerging tooth",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8ceabe63829a4284df953",
                    "isLeafInferred": false,
                    "isLeafStated": false,
                    "v": "2",
                    "conceptId": "367534004",
                    "preferredTerm": "Supernumerary tooth",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000073002",
                        "preferredTerm": "Defined"
                    },
                    "statedDescendants": 7,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8ceace63829a4284e0079",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "710783007",
                    "preferredTerm": "Removable partial denture with loss of occlusal relationship",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                },
                {
                    "_id": "59d8ceade63829a4284e066b",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "718070001",
                    "preferredTerm": "Normal oral mucous membrane and osseointegrated bone tissue surrounding dental implant",
                    "definitionStatus":
                    {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Primitive"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module":
                    {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core"
                    }
                }],
                "details":
                {
                    "total": 226,
                    "refsetId": "721144007"
                }
            }


## Search [/v2/snomed/{edition}/{release}/descriptions?query={query}&searchMode={mode}&lang={language}&statusFilter={statusFilter}&skipTo={skipTo}&returnLimit={returnLimit}&normalize={normalize}&semanticFilter={semanticFilter}&moduleFilter={moduleFilter}&refsetFilter={refsetFilter}]
Performs a text search over the database, selecting mode and other limits.
The search results include the matching descriptions plus a filter descriptor object, allowing to further refining the search by providing new limits.

+ Parameters
    + edition (required, string, `en-edition`) ... Identifier for the SNOMED CT Edition to browse, for example `en-edition` for the International Edition
    + release (required, string, `v20170731`) ... Identifier for the release, usually the release effective time preceded with a `v`.
    + query (required, string, `asthma`) ... String terms to use a query.
    + mode (optional, string, `partialMatching`) ... Search mode, either `partialMatching`, `fullText` or `regex`.
    + language (optional, string, `english`) ... Language for the search, only required for `fullText` mode.
    + statusFilter (optional, string, `english`) ... Value to filter out undesired status, possible values are `activeOnly`, `inactiveOnly` or `activeAndInactive`.
    + semanticFilter (optional, string, `finding`) ... Value to restrict search results to specific an semantic area, possible values are `finding`, `disorder`, `procedure`, etc.
    + moduleFilter (optional, string, `900000000000207008`) ... Value to restrict search results to an specific module, possible values are any valid ModuleId.
    + refsetFilter (optional, string, `450970008`) ... Value to restrict search results to an specific reference set, possible values are any valid Reference Set conceptId.
    + returnLimit (optional, number, `5`) ... Number of results to retrieve in one call.
    + skipTo (optional, number, `0`) ... Number of results to skip, used along with limit to paginate.
    + normalize (optional, string, `true`) ... Wether to normalize search terms or not, should be aligned with index normalization option in the database.

### Search descriptions [GET]
+ Response 200 (application/json)

    + Body

            {
                "matches": [
                {
                    "term": "Asthma",
                    "conceptId": "195967001",
                    "active": true,
                    "conceptActive": true,
                    "fsn": "Asthma (disorder)",
                    "module": "900000000000207008",
                    "definitionStatus": "900000000000074008"
                },
                {
                    "term": "Asthmatic",
                    "conceptId": "195967001",
                    "active": true,
                    "conceptActive": true,
                    "fsn": "Asthma (disorder)",
                    "module": "900000000000207008",
                    "definitionStatus": "900000000000074008"
                },
                {
                    "term": "FH: Asthma",
                    "conceptId": "160377001",
                    "active": true,
                    "conceptActive": true,
                    "fsn": "Family history: Asthma (situation)",
                    "module": "900000000000207008",
                    "definitionStatus": "900000000000073002"
                },
                {
                    "term": "Mild asthma",
                    "conceptId": "370218001",
                    "active": true,
                    "conceptActive": true,
                    "fsn": "Mild asthma (disorder)",
                    "module": "900000000000207008",
                    "definitionStatus": "900000000000074008"
                },
                {
                    "term": "Asthma care",
                    "conceptId": "406162001",
                    "active": true,
                    "conceptActive": true,
                    "fsn": "Asthma management (regime/therapy)",
                    "module": "900000000000207008",
                    "definitionStatus": "900000000000074008"
                }],
                "details":
                {
                    "total": 512,
                    "skipTo": 0,
                    "returnLimit": 5
                },
                "filters":
                {
                    "lang":
                    {
                        "english": 512
                    },
                    "semTag":
                    {
                        "disorder": 272,
                        "situation": 31,
                        "regime/therapy": 27,
                        "environment": 2,
                        "finding": 110,
                        "observable entity": 13,
                        "procedure": 44,
                        "assessment scale": 6,
                        "product": 3,
                        "occupation": 2,
                        "qualifier value": 2
                    },
                    "module":
                    {
                        "900000000000207008": 512
                    },
                    "refsetId":
                    {
                        "450970008": 35,
                        "711112009": 2,
                        "900000000000497000": 512
                    }
                }
            }

# Group Releases

## Release Information [/server/releases]
Provides information on the releases available on the given host

### Releases[GET]

+ Response 200 (application/json)

    + Body

            [
                {
                    "_id": "59d8cfbae63829a428693d60",
                    "resourceSetName": "International Edition",
                    "databaseName": "en-edition",
                    "collectionName": "20170731",
                    "effectiveTime": "20170731",
                    "modules": [
                    {
                        "conceptId": "900000000000012004",
                        "defaultTerm": "SNOMED CT model component",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0
                    },
                    {
                        "conceptId": "715151008",
                        "defaultTerm": "International Classification for Nursing Practice and SNOMED CT equivalency mapping module",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20160131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0
                    },
                    {
                        "conceptId": "715152001",
                        "defaultTerm": "International Health Terminology Standards Development Organisation general and family practitioner module",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20160131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0
                    },
                    {
                        "conceptId": "900000000000207008",
                        "defaultTerm": "SNOMED CT core",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0
                    },
                    {
                        "conceptId": "718292005",
                        "defaultTerm": "International Health Terminology Standards Development Organisation general dentistry diagnostic module",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20170131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0
                    }],
                    "languageRefsets": [
                    {
                        "conceptId": "900000000000509007",
                        "defaultTerm": "US English",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0
                    },
                    {
                        "conceptId": "900000000000508004",
                        "defaultTerm": "GB English",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0
                    }],
                    "refsets": [
                    {
                        "conceptId": "900000000000527005",
                        "defaultTerm": "SAME AS association reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 44877,
                        "type": "ASSOCIATION"
                    },
                    {
                        "conceptId": "900000000000490003",
                        "defaultTerm": "Description inactivation indicator reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 274157,
                        "type": "ATTRIBUTE_VALUE"
                    },
                    {
                        "conceptId": "900000000000524003",
                        "defaultTerm": "MOVED TO association reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 17046,
                        "type": "ASSOCIATION"
                    },
                    {
                        "conceptId": "734139008",
                        "defaultTerm": "Anatomy structure and part association reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20170731",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 317,
                        "type": "ASSOCIATION"
                    },
                    {
                        "conceptId": "450970008",
                        "defaultTerm": "General Practice / Family Practice reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20120731",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 4327,
                        "type": "SIMPLE_REFSET"
                    },
                    {
                        "conceptId": "900000000000530003",
                        "defaultTerm": "ALTERNATIVE association reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 177,
                        "type": "ASSOCIATION"
                    },
                    {
                        "conceptId": "900000000000531004",
                        "defaultTerm": "REFERS TO concept association reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 817,
                        "type": "ASSOCIATION"
                    },
                    {
                        "conceptId": "734138000",
                        "defaultTerm": "Anatomy structure and entire association reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20170731",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 14062,
                        "type": "ASSOCIATION"
                    },
                    {
                        "conceptId": "723264001",
                        "defaultTerm": "Lateralizable body structure reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20170131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 19683,
                        "type": "SIMPLE_REFSET"
                    },
                    {
                        "conceptId": "900000000000489007",
                        "defaultTerm": "Concept inactivation indicator reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 98399,
                        "type": "ATTRIBUTE_VALUE"
                    },
                    {
                        "conceptId": "900000000000523009",
                        "defaultTerm": "POSSIBLY EQUIVALENT TO association reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 32121,
                        "type": "ASSOCIATION"
                    },
                    {
                        "conceptId": "721144007",
                        "defaultTerm": "General dentistry diagnostic reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20170131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 226,
                        "type": "SIMPLE_REFSET"
                    },
                    {
                        "conceptId": "446608001",
                        "defaultTerm": "ICD-O simple map reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 24373,
                        "type": "SIMPLEMAP"
                    },
                    {
                        "conceptId": "900000000000497000",
                        "defaultTerm": "CTV3 simple map",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 443236,
                        "type": "SIMPLEMAP"
                    },
                    {
                        "conceptId": "711112009",
                        "defaultTerm": "ICNP diagnoses simple map reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20150731",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 488,
                        "type": "SIMPLEMAP"
                    },
                    {
                        "conceptId": "900000000000526001",
                        "defaultTerm": "REPLACED BY association reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 5689,
                        "type": "ASSOCIATION"
                    },
                    {
                        "conceptId": "900000000000528000",
                        "defaultTerm": "WAS A association reference set",
                        "definitionStatus": "Primitive",
                        "module": "900000000000012004",
                        "effectiveTime": "20020131",
                        "active": true,
                        "statedDescendants": 0,
                        "inferredDescendants": 0,
                        "count": 21581,
                        "type": "ASSOCIATION"
                    }],
                    "languageRefsetsAbbrev":
                    {},
                    "defaultTermLangCode": "en",
                    "defaultTermType": "900000000000013009",
                    "defaultTermLangRefset": "900000000000509007",
                    "textIndexNormalized": true
                }
            ]
