FORMAT: 1A
HOST: http://browser.ihtsdotools.org/api

# SNOMED CT Snapshot API v2
The SNOMED CT Snapshot REST API provides access to SNOMED CT content snapshot form (only the latest version for all components, see Snapshot definition in the RF2 format description).

This API has been developed by SNOMED International to support lightweight deployments of read-only SNOMED CT terminology servers.

# Group Concepts
Concepts allows access to **SNOMED CT Concepts**

## Concept [/v2/snomed/{edition}/{release}/concepts/{sctid}]
A single Concept with all its details

+ Parameters
    + edition (required, string, `en-edition`) ... Identifier for the SNOMED CT Edition to browse, for example `en-edition` for the International Edition
    + release (required, string, `v20170731`) ... Identifier for the release, usually the release effective time preceded with a `v`.
    + sctid (required, number, `79859009`) ... SNOMED CT Identifier of the concept to retrieve.

### Retrieve a Concept [GET]
+ Response 200 (application/json)

    + Body

            {
                "_id": "598bfd01a0e6f2e897a164fc",
                "memberships": [
                    {
                        "type": "SIMPLEMAP",
                        "referencedComponentId": "79859009",
                        "refset": {
                            "conceptId": "900000000000497000",
                            "preferredTerm": "CTV3 simple map reference set (foundation metadata concept)"
                        },
                        "otherValue": "02B3.",
                        "uuid": "92ca1e61-fff8-51d2-a11c-545d83797bbc",
                        "active": true,
                        "effectiveTime": "20020131",
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    }
                ],
                "descriptions": [
                    {
                        "descriptionId": "132493010",
                        "conceptId": "79859009",
                        "type": {
                            "conceptId": "900000000000013009",
                            "preferredTerm": "Synonym (core metadata concept)"
                        },
                        "languageCode": "en",
                        "term": "Computer programmer",
                        "length": 19,
                        "caseSignificance": {
                            "conceptId": "900000000000448009",
                            "preferredTerm": "Entire term case insensitive (core metadata concept)"
                        },
                        "acceptability": [
                            {
                                "descriptionId": "132493010",
                                "languageReferenceSet": {
                                    "conceptId": "900000000000508004",
                                    "preferredTerm": "Great Britain English language reference set (foundation metadata concept)"
                                },
                                "acceptability": {
                                    "conceptId": "900000000000548007",
                                    "preferredTerm": "Preferred (foundation metadata concept)"
                                },
                                "uuid": "599edffd-9492-57c2-a615-212f9916e23d",
                                "active": true,
                                "effectiveTime": "20020131",
                                "module": {
                                    "conceptId": "900000000000207008",
                                    "preferredTerm": "SNOMED CT core module (core metadata concept)"
                                }
                            },
                            {
                                "descriptionId": "132493010",
                                "languageReferenceSet": {
                                    "conceptId": "900000000000509007",
                                    "preferredTerm": "United States of America English language reference set (foundation metadata concept)"
                                },
                                "acceptability": {
                                    "conceptId": "900000000000548007",
                                    "preferredTerm": "Preferred (foundation metadata concept)"
                                },
                                "uuid": "63ea720a-e2c4-5e85-9758-4536606ad0b3",
                                "active": true,
                                "effectiveTime": "20080131",
                                "module": {
                                    "conceptId": "900000000000207008",
                                    "preferredTerm": "SNOMED CT core module (core metadata concept)"
                                }
                            }
                        ],
                        "active": true,
                        "effectiveTime": "20170731",
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    },
                    {
                        "descriptionId": "504232014",
                        "conceptId": "79859009",
                        "type": {
                            "conceptId": "900000000000013009",
                            "preferredTerm": "Synonym (core metadata concept)"
                        },
                        "languageCode": "en",
                        "term": "Computer programr",
                        "length": 17,
                        "caseSignificance": {
                            "conceptId": "900000000000020002",
                            "preferredTerm": "Only initial character case insensitive (core metadata concept)"
                        },
                        "active": false,
                        "effectiveTime": "20080131",
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    },
                    {
                        "descriptionId": "820955016",
                        "conceptId": "79859009",
                        "type": {
                            "conceptId": "900000000000003001",
                            "preferredTerm": "Fully specified name (core metadata concept)"
                        },
                        "languageCode": "en",
                        "term": "Computer programmer (occupation)",
                        "length": 32,
                        "caseSignificance": {
                            "conceptId": "900000000000448009",
                            "preferredTerm": "Entire term case insensitive (core metadata concept)"
                        },
                        "acceptability": [
                            {
                                "descriptionId": "820955016",
                                "languageReferenceSet": {
                                    "conceptId": "900000000000508004",
                                    "preferredTerm": "Great Britain English language reference set (foundation metadata concept)"
                                },
                                "acceptability": {
                                    "conceptId": "900000000000548007",
                                    "preferredTerm": "Preferred (foundation metadata concept)"
                                },
                                "uuid": "26b45dfb-3d13-52c4-b6c5-f3cab43b5ad6",
                                "active": true,
                                "effectiveTime": "20020131",
                                "module": {
                                    "conceptId": "900000000000207008",
                                    "preferredTerm": "SNOMED CT core module (core metadata concept)"
                                }
                            },
                            {
                                "descriptionId": "820955016",
                                "languageReferenceSet": {
                                    "conceptId": "900000000000509007",
                                    "preferredTerm": "United States of America English language reference set (foundation metadata concept)"
                                },
                                "acceptability": {
                                    "conceptId": "900000000000548007",
                                    "preferredTerm": "Preferred (foundation metadata concept)"
                                },
                                "uuid": "772accf1-7627-5366-b1b8-1f246416521e",
                                "active": true,
                                "effectiveTime": "20020131",
                                "module": {
                                    "conceptId": "900000000000207008",
                                    "preferredTerm": "SNOMED CT core module (core metadata concept)"
                                }
                            }
                        ],
                        "active": true,
                        "effectiveTime": "20170731",
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    }
                ],
                "relationships": [
                    {
                        "relationshipId": "4076360022",
                        "type": {
                            "conceptId": "116680003",
                            "preferredTerm": "Is a (attribute)"
                        },
                        "destination": {
                            "conceptId": "106297009",
                            "preferredTerm": "Statistician, mathematician, systems analyst/related technician (occupation)",
                            "fullySpecifiedName": "Statistician, mathematician, systems analyst/related technician (occupation)",
                            "definitionStatus": {
                                "conceptId": "900000000000074008",
                                "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                            },
                            "statedDescendants": 13,
                            "inferredDescendants": 13,
                            "active": true,
                            "effectiveTime": "20020131",
                            "module": {
                                "conceptId": "900000000000207008",
                                "preferredTerm": "SNOMED CT core module (core metadata concept)"
                            }
                        },
                        "sourceId": "79859009",
                        "relationshipGroup": 0,
                        "characteristicType": {
                            "conceptId": "900000000000010007",
                            "preferredTerm": "Stated relationship (core metadata concept)"
                        },
                        "modifier": {
                            "conceptId": "900000000000451002",
                            "preferredTerm": "Existential restriction modifier (core metadata concept)"
                        },
                        "active": true,
                        "effectiveTime": "20080731",
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    },
                    {
                        "relationshipId": "4076361021",
                        "type": {
                            "conceptId": "116680003",
                            "preferredTerm": "Is a (attribute)"
                        },
                        "destination": {
                            "conceptId": "158832009",
                            "preferredTerm": "Systems analyst/computer programmer (occupation)",
                            "fullySpecifiedName": "Systems analyst/computer programmer (occupation)",
                            "definitionStatus": {
                                "conceptId": "900000000000074008",
                                "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                            },
                            "statedDescendants": 4,
                            "inferredDescendants": 4,
                            "active": true,
                            "effectiveTime": "20020131",
                            "module": {
                                "conceptId": "900000000000207008",
                                "preferredTerm": "SNOMED CT core module (core metadata concept)"
                            }
                        },
                        "sourceId": "79859009",
                        "relationshipGroup": 0,
                        "characteristicType": {
                            "conceptId": "900000000000010007",
                            "preferredTerm": "Stated relationship (core metadata concept)"
                        },
                        "modifier": {
                            "conceptId": "900000000000451002",
                            "preferredTerm": "Existential restriction modifier (core metadata concept)"
                        },
                        "active": true,
                        "effectiveTime": "20080731",
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    },
                    {
                        "relationshipId": "277869024",
                        "type": {
                            "conceptId": "116680003",
                            "preferredTerm": "Is a (attribute)"
                        },
                        "destination": {
                            "conceptId": "158832009",
                            "preferredTerm": "Systems analyst/computer programmer (occupation)",
                            "fullySpecifiedName": "Systems analyst/computer programmer (occupation)",
                            "definitionStatus": {
                                "conceptId": "900000000000074008",
                                "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                            },
                            "statedDescendants": 4,
                            "inferredDescendants": 4,
                            "active": true,
                            "effectiveTime": "20020131",
                            "module": {
                                "conceptId": "900000000000207008",
                                "preferredTerm": "SNOMED CT core module (core metadata concept)"
                            }
                        },
                        "sourceId": "79859009",
                        "relationshipGroup": 0,
                        "characteristicType": {
                            "conceptId": "900000000000011006",
                            "preferredTerm": "Inferred relationship (core metadata concept)"
                        },
                        "modifier": {
                            "conceptId": "900000000000451002",
                            "preferredTerm": "Existential restriction modifier (core metadata concept)"
                        },
                        "active": true,
                        "effectiveTime": "20020131",
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    },
                    {
                        "relationshipId": "277870020",
                        "type": {
                            "conceptId": "116680003",
                            "preferredTerm": "Is a (attribute)"
                        },
                        "destination": {
                            "conceptId": "106297009",
                            "preferredTerm": "Statistician, mathematician, systems analyst/related technician (occupation)",
                            "fullySpecifiedName": "Statistician, mathematician, systems analyst/related technician (occupation)",
                            "definitionStatus": {
                                "conceptId": "900000000000074008",
                                "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                            },
                            "statedDescendants": 13,
                            "inferredDescendants": 13,
                            "active": true,
                            "effectiveTime": "20020131",
                            "module": {
                                "conceptId": "900000000000207008",
                                "preferredTerm": "SNOMED CT core module (core metadata concept)"
                            }
                        },
                        "sourceId": "79859009",
                        "relationshipGroup": 0,
                        "characteristicType": {
                            "conceptId": "900000000000011006",
                            "preferredTerm": "Inferred relationship (core metadata concept)"
                        },
                        "modifier": {
                            "conceptId": "900000000000451002",
                            "preferredTerm": "Existential restriction modifier (core metadata concept)"
                        },
                        "active": true,
                        "effectiveTime": "20020131",
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    }
                ],
                "isLeafInferred": true,
                "isLeafStated": true,
                "v": "2",
                "conceptId": "79859009",
                "preferredTerm": "Computer programmer (occupation)",
                "fullySpecifiedName": "Computer programmer (occupation)",
                "definitionStatus": {
                    "conceptId": "900000000000074008",
                    "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                },
                "statedDescendants": 0,
                "inferredDescendants": 0,
                "active": true,
                "effectiveTime": "20020131",
                "module": {
                    "conceptId": "900000000000207008",
                    "preferredTerm": "SNOMED CT core module (core metadata concept)"
                }
            }

## Children [/v2/snomed/{edition}/{release}/concepts/{sctid}/children?form={form}]
Lists all children of a concept, in the SNOMED CT hierarchy. Each child is retrieved in a summary form, called Concept Descriptor.

+ Parameters
    + edition (required, string, `en-edition`) ... Identifier for the SNOMED CT Edition to browse, for example `en-edition` for the International Edition
    + release (required, string, `v20170731`) ... Identifier for the release, usually the release effective time preceded with a `v`.
    + sctid (required, number, `123037004`) ... SNOMED CT Identifier of the concept to retrieve.
    + form (required, string, `inferred`) ... Characteristic type of the Is-a hierarchy, either `stated` or `inferred`.

### Retrieve Children [GET]
+ Response 200 (application/json)

    + Body

            [
                {
                    "_id": "598bfcdca0e6f2e897a06874",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "159054003",
                    "preferredTerm": "Process description writer (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    }
                },
                {
                    "_id": "598bfce3a0e6f2e897a0996b",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "159053009",
                    "preferredTerm": "Instruction writer (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    }
                },
                {
                    "_id": "598bfcf4a0e6f2e897a10ee0",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "159055002",
                    "preferredTerm": "Program writer (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    }
                },
                {
                    "_id": "598bfcf7a0e6f2e897a12382",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "159059008",
                    "preferredTerm": "Trainee writer (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    }
                },
                {
                    "_id": "598bfd17a0e6f2e897a1fe1c",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "67790005",
                    "preferredTerm": "Publicity writer (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    }
                },
                {
                    "_id": "598bfd25a0e6f2e897a26215",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "89007006",
                    "preferredTerm": "Technical writer (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    }
                },
                {
                    "_id": "598bfd41a0e6f2e897a32952",
                    "isLeafInferred": true,
                    "isLeafStated": true,
                    "v": "2",
                    "conceptId": "47667004",
                    "preferredTerm": "Advertising copywriter (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "statedDescendants": 0,
                    "active": true,
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    }
                }
            ]


## Parents [/v2/snomed/{edition}/{release}/concepts/{sctid}/parents?form={form}]
Lists all parents of a concept, in the SNOMED CT hierarchy. Each parent is retrieved in a summary form, called Concept Descriptor.

+ Parameters
    + edition (required, string, `en-edition`) ... Identifier for the SNOMED CT Edition to browse, for example `en-edition` for the International Edition
    + release (required, string, `v20170731`) ... Identifier for the release, usually the release effective time preceded with a `v`.
    + sctid (required, number, `79859009`) ... SNOMED CT Identifier of the concept to retrieve.
    + form (required, string, `inferred`) ... Characteristic type of the Is-a hierarchy, either `stated` or `inferred`.

### Retrieve Parents [GET]
+ Response 200 (application/json)

    + Body

            [
                {
                    "conceptId": "106297009",
                    "preferredTerm": "Statistician, mathematician, systems analyst/related technician (occupation)",
                    "fullySpecifiedName": "Statistician, mathematician, systems analyst/related technician (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    },
                    "statedDescendants": 13
                },
                {
                    "conceptId": "158832009",
                    "preferredTerm": "Systems analyst/computer programmer (occupation)",
                    "fullySpecifiedName": "Systems analyst/computer programmer (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    },
                    "statedDescendants": 4
                },
                {
                    "conceptId": "158832009",
                    "preferredTerm": "Systems analyst/computer programmer (occupation)",
                    "fullySpecifiedName": "Systems analyst/computer programmer (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    },
                    "statedDescendants": 4
                },
                {
                    "conceptId": "106297009",
                    "preferredTerm": "Statistician, mathematician, systems analyst/related technician (occupation)",
                    "fullySpecifiedName": "Statistician, mathematician, systems analyst/related technician (occupation)",
                    "definitionStatus": {
                        "conceptId": "900000000000074008",
                        "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                    },
                    "module": {
                        "conceptId": "900000000000207008",
                        "preferredTerm": "SNOMED CT core module (core metadata concept)"
                    },
                    "statedDescendants": 13
                }
            ]


## Members [/v2/snomed/{edition}/{release}/concepts/{sctid}/members?limit={limit}&paginate={page}]
Lists all reference set members of a concept. Each member is retrieved in a summary form, called Concept Descriptor.
Only concepts that are reference sets will include members.
The concept details describe all the reference sets where a concept is member in, called memberships, and can be retrieved with the /concepts/id call.

+ Parameters
    + edition (required, string, `en-edition`) ... Identifier for the SNOMED CT Edition to browse, for example `en-edition` for the International Edition
    + release (required, string, `v20170731`) ... Identifier for the release, usually the release effective time preceded with a `v`.
    + sctid (required, number, `105997008`) ... SNOMED CT Identifier of the concept to retrieve.
    + limit (optional, number, `5`) ... Number of concepts to retrieve on this call (page size).
    + page (optional, number, `1`) ... Page number to retrieve.

### Retrieve Reference set members [GET]
+ Response 200 (application/json)

    + Body

            {
                "members": [
                    {
                        "_id": "598bfc7da0e6f2e8979db4ab",
                        "isLeafInferred": false,
                        "isLeafStated": false,
                        "v": "2",
                        "conceptId": "441935006",
                        "preferredTerm": "Acquired absence of all teeth (disorder)",
                        "definitionStatus": {
                            "conceptId": "900000000000074008",
                            "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                        },
                        "statedDescendants": 19,
                        "active": true,
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    },
                    {
                        "_id": "598bfc7ea0e6f2e8979dba03",
                        "isLeafInferred": true,
                        "isLeafStated": true,
                        "v": "2",
                        "conceptId": "234973008",
                        "preferredTerm": "Submerging tooth (disorder)",
                        "definitionStatus": {
                            "conceptId": "900000000000074008",
                            "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                        },
                        "statedDescendants": 0,
                        "active": true,
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    },
                    {
                        "_id": "598bfc7ea0e6f2e8979dbc83",
                        "isLeafInferred": false,
                        "isLeafStated": false,
                        "v": "2",
                        "conceptId": "367534004",
                        "preferredTerm": "Supernumerary tooth (disorder)",
                        "definitionStatus": {
                            "conceptId": "900000000000073002",
                            "preferredTerm": "Sufficiently defined concept definition status (core metadata concept)"
                        },
                        "statedDescendants": 7,
                        "active": true,
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    },
                    {
                        "_id": "598bfc7fa0e6f2e8979dc3ad",
                        "isLeafInferred": true,
                        "isLeafStated": true,
                        "v": "2",
                        "conceptId": "710783007",
                        "preferredTerm": "Removable partial denture with loss of occlusal relationship (finding)",
                        "definitionStatus": {
                            "conceptId": "900000000000074008",
                            "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                        },
                        "statedDescendants": 0,
                        "active": true,
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    },
                    {
                        "_id": "598bfc80a0e6f2e8979dc99c",
                        "isLeafInferred": true,
                        "isLeafStated": true,
                        "v": "2",
                        "conceptId": "718070001",
                        "preferredTerm": "Normal oral mucous membrane and osseointegrated bone tissue surrounding dental implant (finding)",
                        "definitionStatus": {
                            "conceptId": "900000000000074008",
                            "preferredTerm": "Necessary but not sufficient concept definition status (core metadata concept)"
                        },
                        "statedDescendants": 0,
                        "active": true,
                        "module": {
                            "conceptId": "900000000000207008",
                            "preferredTerm": "SNOMED CT core module (core metadata concept)"
                        }
                    }
                ],
                "details": {
                    "total": 226,
                    "refsetId": "721144007"
                }
            }


## Search [/v2/snomed/{edition}/{release}/descriptions?query={query}&searchMode={mode}&lang={language}&statusFilter={statusFilter}&skipTo={skipTo}&returnLimit={returnLimit}&normalize={normalize}&semanticFilter={semanticFilter}&moduleFilter={moduleFilter}&langFilter={langFilter}&refsetFilter={refsetFilter}]
Performs a text search over the database, selecting mode and other limits.
The search results include the matching descriptions plus a filter descriptor object, allowing to further refining the search by providing new limits.

+ Parameters
    + edition (required, string, `en-edition`) ... Identifier for the SNOMED CT Edition to browse, for example `en-edition` for the International Edition
    + release (required, string, `v20170731`) ... Identifier for the release, usually the release effective time preceded with a `v`.
    + query (required, string, `asthma`) ... String terms to use a query.
    + mode (optional, string, `partialMatching`) ... Search mode, either `partialMatching`, `fullText` or `regex`.
    + language (optional, string, `english`) ... Languge for the search, only required for `fullText` mode.
    + statusFilter (optional, string, `english`) ... Value to filter out undesired status, possible values are `activeOnly`, `inactiveOnly` or `activeAndInactive`.
    + semanticFilter (optional, string, `findng`) ... Value to restrict search results to specififc an semantic area, possible values are `finding`, `disorder`, `procedure`, etc.
    + moduleFilter (optional, string, `900000000000207008`) ... Value to restrict search results to an specififc module, possible values are any valid ModuleId.
    + langFilter (optional, string, `en`) ... Value to restrict search results to an specififc language code, possible values are any valid language code.
    + refsetFilter (optional, string, `450970008`) ... Value to restrict search results to an specififc reference set, possible values are any valid Reference Set conceptId.
    + returnLimit (optional, number, `5`) ... Number of results to retrieve in one call.
    + skipTo (optional, number, `0`) ... Number of results to skip, used along with limit to paginate.
    + normalize (optional, string, `true`) ... Wether to normalize search terms or not, should be aligned with index normalization option in the database.

### Search descriptions [GET]
+ Response 200 (application/json)

    + Body

            {
               "matches":[
                  {
                     "term":"Asthma",
                     "conceptId":"195967001",
                     "active":true,
                     "conceptActive":true,
                     "fsn":"Asthma (disorder)",
                     "module":"900000000000207008",
                     "definitionStatus":"Primitive"
                  },
                  {
                     "term":"Asthmatic",
                     "conceptId":"195967001",
                     "active":true,
                     "conceptActive":true,
                     "fsn":"Asthma (disorder)",
                     "module":"900000000000207008",
                     "definitionStatus":"Primitive"
                  },
                  {
                     "term":"FH: Asthma",
                     "conceptId":"160377001",
                     "active":true,
                     "conceptActive":true,
                     "fsn":"Family history: Asthma (situation)",
                     "module":"900000000000207008",
                     "definitionStatus":"Fully defined"
                  },
                  {
                     "term":"Wood asthma",
                     "conceptId":"56968009",
                     "active":true,
                     "conceptActive":true,
                     "fsn":"Wood asthma (disorder)",
                     "module":"900000000000207008",
                     "definitionStatus":"Fully defined"
                  },
                  {
                     "term":"Asthma care",
                     "conceptId":"406162001",
                     "active":true,
                     "conceptActive":true,
                     "fsn":"Asthma management (regime/therapy)",
                     "module":"900000000000207008",
                     "definitionStatus":"Primitive"
                  }
               ],
               "details":{
                  "total":379,
                  "skipTo":0,
                  "returnLimit":5
               },
               "filters":{
                  "lang":{
                     "english":379
                  },
                  "semTag":{
                     "disorder":175,
                     "situation":19,
                     "regime/therapy":31,
                     "environment":2,
                     "finding":90,
                     "observable entity":11,
                     "procedure":39,
                     "assessment scale":6,
                     "occupation":2,
                     "qualifier value":2,
                     "product":2
                  },
                  "module":{
                     "900000000000207008":379
                  },
                  "refsetId":{
                     "900000000000497000":379,
                     "900000000000498005":379
                  }
               }
            }

# Group Releases

## Release Information [/server/releases]
Provides information on the releases available on the given host

### Releases[GET]

+ Response 200 (application/json)

    + Body

            [
              {
                "_id": "56c42cfc7df006c561178579",
                "resourceSetName": "International Edition",
                "effectiveTime": "20160131",
                "databaseName": "en-edition",
                "collectionName": "20160131",
                "expirationDate": "20170801",
                "modules": [
                  {
                    "conceptId": "900000000000012004",
                    "defaultTerm": "SNOMED CT model component module (core metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "conceptId": "900000000000207008",
                    "defaultTerm": "SNOMED CT core module (core metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  }
                ],
                "languageRefsets": [
                  {
                    "conceptId": "900000000000508004",
                    "defaultTerm": "Great Britain English language reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "conceptId": "900000000000509007",
                    "defaultTerm": "United States of America English language reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  }
                ],
                "refsets": [
                  {
                    "count": 16992,
                    "type": "ASSOCIATION",
                    "conceptId": "900000000000524003",
                    "defaultTerm": "MOVED TO association reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 24015,
                    "type": "SIMPLEMAP",
                    "conceptId": "446608001",
                    "defaultTerm": "ICD-O simple map reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 5558,
                    "type": "ASSOCIATION",
                    "conceptId": "900000000000526001",
                    "defaultTerm": "REPLACED BY association reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 424758,
                    "type": "SIMPLEMAP",
                    "conceptId": "900000000000498005",
                    "defaultTerm": "SNOMED RT identifier simple map (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 424758,
                    "type": "SIMPLEMAP",
                    "conceptId": "900000000000497000",
                    "defaultTerm": "CTV3 simple map reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 258304,
                    "type": "ATTRIBUTE_VALUE",
                    "conceptId": "900000000000490003",
                    "defaultTerm": "Description inactivation indicator attribute value reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 21402,
                    "type": "ASSOCIATION",
                    "conceptId": "900000000000528000",
                    "defaultTerm": "WAS A association reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 44606,
                    "type": "ASSOCIATION",
                    "conceptId": "900000000000527005",
                    "defaultTerm": "SAME AS association reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 177,
                    "type": "ASSOCIATION",
                    "conceptId": "900000000000530003",
                    "defaultTerm": "ALTERNATIVE association reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 31957,
                    "type": "ASSOCIATION",
                    "conceptId": "900000000000523009",
                    "defaultTerm": "POSSIBLY EQUIVALENT TO association reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 97372,
                    "type": "ATTRIBUTE_VALUE",
                    "conceptId": "900000000000489007",
                    "defaultTerm": "Concept inactivation indicator attribute value reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  },
                  {
                    "count": 833,
                    "type": "ASSOCIATION",
                    "conceptId": "900000000000531004",
                    "defaultTerm": "REFERS TO concept association reference set (foundation metadata concept)",
                    "definitionStatus": "Primitive",
                    "statedDescendants": 0,
                    "inferredDescendants": 0,
                    "active": true,
                    "effectiveTime": "20020131",
                    "module": "900000000000012004"
                  }
                ],
                "languageRefsetsAbbrev": {},
                "defaultTermLangCode": "en",
                "defaultTermType": "900000000000003001",
                "defaultTermLangRefset": "900000000000509007",
                "textIndexNormalized": true
              }
            ]
