version: '2'
services:
  web:
    build: .
    ports:
      - "9999:9999"
      - "35729:35729"
    environment:
      - NODE_ENV=development
      - MONGO_DB_CONN=web:27017
    volumes_from:
      - db-data
    networks:
      - snomed
  db-data:
    image: mongo:latest
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true
networks:
  snomed:
    driver: bridge
