version: '2.1'
services:
  db:
    image: mongo:latest
    ports:
     - "27017:27017"
    volumes_from:
        - db-data
    networks:
      snomed:
        aliases:
         - db


  db-data:
    image: mongo:latest
    volumes:
      - ~/mongo/data:/data/db
      - ~/mongo/lib:/var/lib/mongodb
      - ~/mongo/log:/var/log/mongodb
    entrypoint: /bin/true

  snomed-api:
    build: .
    links:
     - db
    ports:
     - "3000:3000"
     - "35729:35729"
    environment:
     - NODE_ENV=development
     - MONGO_DB_CONN=db:27017
    networks:
        - snomed
    command: ["./wait-for-it.sh", "db:27017", "--", "node", "app.js"]


networks:
  snomed:
    driver: bridge
