version: '2'
services:
  web:
    build: .
    links:
     - db
    ports:
     - "3000:3000"
     - "35729:35729"
    environment:
     - NODE_ENV=development
     - MONGO_DB_CONN=db:27017
    networks:
        - snomed
  db:
    image: mongo:latest
    ports:
     - "27017:27017"
    volumes_from:
        - db-data
    networks:
        - snomed
  db-data:
    image: mongo:latest
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true
networks:
  snomed:
    driver: bridge
